# Generated by Django 3.1.4 on 2021-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year_issue', models.DateField()),
                ('number_books', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
