# Generated by Django 3.0.4 on 2021-03-07 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbnCord', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=60)),
                ('bookYearOfIssue', models.DateField()),
                ('systemRegistDay', models.DateField(auto_now_add=True)),
                ('money', models.IntegerField(default=0)),
                ('numBooks', models.IntegerField(default=0)),
                ('majorClass', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
                ('middleClass', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
            ],
        ),
        migrations.CreateModel(
            name='Lending_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDjangoID', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('borrowedBook', models.CharField(max_length=100)),
                ('bookDjangoID', models.IntegerField(default=0)),
                ('someProcessing', models.CharField(max_length=10)),
                ('processingDay', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registDay', models.DateField(auto_now_add=True)),
                ('bookDetails', models.CharField(max_length=400)),
                ('bookStatus', models.CharField(max_length=10)),
                ('Book_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM_System.Book_stock')),
            ],
        ),
    ]
